/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const React: typeof import('react')['default']
  const useEffect: typeof import('react')['useEffect']
  const useState: typeof import('react')['useState']
}
